In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\anil\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anil\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\anil\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\anil\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.0/9.9 MB 1.9 MB/s eta 0:00:06
   ---------------------------------------- 0.1/9.9 MB 104.9 kB/s eta 0:01:34
   ---------------------------------------- 0.1/9.9 MB 128.5 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.9 MB 128.5 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.9 MB 128.5 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.9 MB 128.5 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.9 MB 128.5 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.9 MB 128.5 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.9 MB 128.5 kB/s eta 0:01:17
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
   ---------------------------------------- 0.1/9.9 MB 100.1 kB/s eta 0:01:38
    --------------------------------------- 0.1/9.9 MB 87.8 kB/s eta 0:01:52
    --------------------------------------- 0.1/9.9 MB 87.8 kB/s eta 0:01:52
    --------------------------------------- 0.2/9.9 MB 120.9 kB/s eta 0:01:21
    --------------------------------------- 0.2/9.9 MB 131.0 kB/s eta 0:01:14
    --------------------------------------- 0.2/9.9 MB 131.0 kB/s eta 0:01:14
    --------------------------------------- 0.2/9.9 MB 131.0 kB/s eta 0:01:14
    --------------------------------------- 0.2/9.9 MB 131.0 kB/s eta 0:01:14
    --------------------------------------- 0.2/9.9 MB 131.0 kB/s eta 0:01:14
    --------------------------------------- 0.2/9.9 MB 131.0 kB/s eta 0:01:14
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 128.9 kB/s eta 0:01:15
   - -------------------------------------- 0.3/9.9 MB 129.3 kB/s eta 0:01:15
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 151.9 kB/s eta 0:01:03
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   - -------------------------------------- 0.4/9.9 MB 141.8 kB/s eta 0:01:08
   -- ------------------------------------- 0.5/9.9 MB 158.9 kB/s eta 0:01:00
   -- ------------------------------------- 0.5/9.9 MB 158.9 kB/s eta 0:01:00
   -- ------------------------------------- 0.5/9.9 MB 158.9 kB/s eta 0:01:00
   -- ------------------------------------- 0.5/9.9 MB 158.9 kB/s eta 0:01:00
   -- ------------------------------------- 0.5/9.9 MB 158.9 kB/s eta 0:01:00
   -- ------------------------------------- 0.5/9.9 MB 158.9 kB/s eta 0:01:00
   -- ------------------------------------- 0.5/9.9 MB 158.9 kB/s eta 0:01:00
   -- ------------------------------------- 0.5/9.9 MB 148.9 kB/s eta 0:01:04
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.5/9.9 MB 151.2 kB/s eta 0:01:02
   -- ------------------------------------- 0.7/9.9 MB 151.1 kB/s eta 0:01:01
   --- ------------------------------------ 0.8/9.9 MB 161.6 kB/s eta 0:00:57
   --- ------------------------------------ 0.8/9.9 MB 161.6 kB/s eta 0:00:57
   --- ------------------------------------ 0.8/9.9 MB 161.6 kB/s eta 0:00:57
   --- ------------------------------------ 0.8/9.9 MB 161.6 kB/s eta 0:00:57
   --- ------------------------------------ 0.8/9.9 MB 161.6 kB/s eta 0:00:57
   --- ------------------------------------ 0.8/9.9 MB 161.6 kB/s eta 0:00:57
   --- ------------------------------------ 0.8/9.9 MB 161.6 kB/s eta 0:00:57
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.8/9.9 MB 154.1 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   --- ------------------------------------ 0.9/9.9 MB 152.7 kB/s eta 0:01:00
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 143.5 kB/s eta 0:01:03
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.0/9.9 MB 138.9 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 138.3 kB/s eta 0:01:04
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 133.1 kB/s eta 0:01:07
   ---- ----------------------------------- 1.1/9.9 MB 132.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 134.9 kB/s eta 0:01:05
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.8 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ---- ----------------------------------- 1.2/9.9 MB 130.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.2/9.9 MB 128.7 kB/s eta 0:01:08
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 128.6 kB/s eta 0:01:07
   ----- ---------------------------------- 1.3/9.9 MB 126.1 kB/s eta 0:01:09
   ----- ---------------------------------- 1.3/9.9 MB 126.1 kB/s eta 0:01:09
   ----- ---------------------------------- 1.3/9.9 MB 126.1 kB/s eta 0:01:09

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [25]:
data={'Name' : ['Alice','Bob','Martha','Adam'],
       'Age' : [25,26,23,24],}
df = pd.DataFrame(data)
print(data)

{'Name': ['Alice', 'Bob', 'Martha', 'Adam'], 'Age': [25, 26, 23, 24]}

In [12]:
datalist=[['Alice',25],['Bob',26]]
df=pd.DataFrame(datalist,columns=['Name','Age'])

In [5]:
df.head()

     Name  Age
0   Alice   25
1     Bob   26
2  Martha   23
3    Adam   24

In [6]:
df.tail()

     Name  Age
0   Alice   25
1     Bob   26
2  Martha   23
3    Adam   24

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [8]:
df.describe()

             Age
count   4.000000
mean   24.500000
std     1.290994
min    23.000000
25%    23.750000
50%    24.500000
75%    25.250000
max    26.000000

In [9]:
df['Name']

0     Alice
1       Bob
2    Martha
3      Adam
Name: Name, dtype: str

In [10]:
df['Age']

0    25
1    26
2    23
3    24
Name: Age, dtype: int64

In [12]:
df.loc[2]

Name    Martha
Age         23
Name: 2, dtype: object

In [16]:
df.iloc[1]

Name    Bob
Age      26
Name: 1, dtype: object

In [8]:
df[df['Age']>23]

    Name  Age
0  Alice   25
1    Bob   26
3   Adam   24

In [26]:
df['Gender'] = ['F','M','F','M']

In [10]:
df.drop('Age',axis=1,inplace=True)

In [11]:
df.isnull()

    Name
0  False
1  False
2  False
3  False

In [12]:
df.dropna()

     Name
0   Alice
1     Bob
2  Martha
3    Adam

In [14]:
df.fillna(0)

     Name
0   Alice
1     Bob
2  Martha
3    Adam

In [22]:
df.groupby('Gender')['Age'].mean()

Gender
F    24.0
M    25.0
Name: Age, dtype: float64

In [31]:
df1=pd.DataFrame({'key':[1,2,3],
                 'Name':['Max','Jonas','Noah']})

df2=pd.DataFrame({'key':[1,2,3],
                 'Name':['Susan','Peggy','Agnes']})
pd.merge(df1,df2,on='key')

   key Name_x Name_y
0    1    Max  Susan
1    2  Jonas  Peggy
2    3   Noah  Agnes

In [34]:
df1=pd.DataFrame({'key':[1,2,3],
                 'Name':['Max','Jonas','Noah']})

df2=pd.DataFrame({'Stream':['CSE','ECE','EEE'],
                 'Type':['Part time','Full time','Hybrid']})
df1.join(df2)

   key   Name Stream       Type
0    1    Max    CSE  Part time
1    2  Jonas    ECE  Full time
2    3   Noah    EEE     Hybrid

In [39]:
open('data.csv','w').close()

In [55]:
df.to_csv('data.csv', index = False)

In [41]:
df=pd.read_csv('data.csv')

In [44]:
open('output.csv','w').close()

In [46]:
df.to_csv('output.csv',index=False)

In [47]:
print(df)

     Name  Age Gender
0   Alice   25      F
1     Bob   26      M
2  Martha   23      F
3    Adam   24      M

In [48]:
df.sort_values('Age')

     Name  Age Gender
2  Martha   23      F
3    Adam   24      M
0   Alice   25      F
1     Bob   26      M

In [49]:
df['Age'].apply(lambda x:x+1)

0    26
1    27
2    24
3    25
Name: Age, dtype: int64

In [50]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob', 'Martha', 'Adam']
Length: 4, dtype: str

In [52]:
df['Age'].value_counts()

Age
25    1
26    1
23    1
24    1
Name: count, dtype: int64